# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da485934c0de6109df35d932fa8d4779f980c995d68cae91f3cf46ec85e3e9a2ef8625f73ca978f31060f22ca2b773e8d343c1465c34a93bdd350f88a828aa59

test:
  secret_key_base: 71f07506ca0b39b5dfff09769d31cf5b28d7d784d77a86dfea1c230e4d3b88e786fc878d9c0d4abb591f8fc304ef3f220d2ddb7f267d5c7f7eb5a5fc2102070e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
